/**
 * Cultural Product Bank catalogue (Option 1: separate SKU per pack/format).
 * India, Pakistan, Bangladesh, and Arabic pantry staples with pack size in the name.
 * Images: stable Unsplash food/grocery photos (nature of halal grocery retail).
 */

export type CulturalProductSeed = {
  name: string;
  slug: string;
  barcode: string;
  sku: string;
  description: string;
  category: string;
  price: number;
  tags: string[];
  imageUrl: string;
};

/**
 * Local grocery photography (verified / generated).
 * Files live in `prisma/product-images/` and are copied to `/uploads/products/` on seed.
 * Same pack sizes share one family image; distinct vegetables get distinct images.
 */
const img = (file: string) => `/uploads/products/${file}`;

const IMG = {
  basmati: img('rice.jpg'),
  sellaRice: img('sella-rice.jpg'),
  jeeraRice: img('jeera-rice.jpg'),
  brokenRice: img('broken-rice.jpg'),
  bulgur: img('bulgur.jpg'),
  freekeh: img('freekeh.jpg'),
  couscous: img('couscous.jpg'),
  papadum: img('papadum.jpg'),
  vermicelli: img('vermicelli.jpg'),
  pearlBarley: img('pearl-barley.jpg'),
  toorDal: img('toor-dal.jpg'),
  masoorDal: img('masoor-dal.jpg'),
  moongDal: img('moong-dal.jpg'),
  uradDal: img('urad-dal.jpg'),
  chanaDal: img('chana-dal.jpg'),
  chickpeas: img('chickpeas.jpg'),
  wholeMoong: img('whole-moong.jpg'),
  favaBeans: img('fava-beans.jpg'),
  kidneyBeans: img('kidney-beans.jpg'),
  flour: img('flour.jpg'),
  besan: img('besan.jpg'),
  riceFlour: img('rice-flour.jpg'),
  suji: img('suji.jpg'),
  cornflour: img('cornflour.jpg'),
  cumin: img('cumin.jpg'),
  corianderPowder: img('coriander-powder.jpg'),
  garamMasala: img('garam-masala.jpg'),
  biryaniMasala: img('biryani-masala.jpg'),
  mustardSeeds: img('mustard-seeds.jpg'),
  fenugreekSeeds: img('fenugreek-seeds.jpg'),
  cardamom: img('cardamom.jpg'),
  cloves: img('cloves.jpg'),
  cinnamon: img('cinnamon.jpg'),
  blackPepper: img('black-pepper.jpg'),
  bayLeaves: img('bay-leaves.jpg'),
  zaatar: img('zaatar.jpg'),
  sumac: img('sumac.jpg'),
  baharat: img('baharat.jpg'),
  panchPhoron: img('panch-phoron.jpg'),
  chilli: img('chilli.jpg'),
  kashmiriChilli: img('kashmiri-chilli.jpg'),
  greenChilli: img('greenChilli.jpg'),
  turmeric: img('turmeric.jpg'),
  oil: img('oil.jpg'),
  sunflowerOil: img('sunflower-oil.jpg'),
  oliveOil: img('olive-oil.jpg'),
  ghee: img('ghee.jpg'),
  chicken: img('chicken.jpg'),
  chickenThighs: img('chicken-thighs.jpg'),
  chickenWhole: img('chicken-whole.jpg'),
  chickenBreast: img('chicken-breast.jpg'),
  chickenKeema: img('chicken-keema.jpg'),
  chickenDrumsticks: img('chicken-drumsticks.jpg'),
  chickenWings: img('chicken-wings.jpg'),
  chickenLegs: img('chicken-legs.jpg'),
  chickenFrozen: img('chicken-frozen.jpg'),
  lamb: img('lamb.jpg'),
  lambMutton: img('lamb-mutton.jpg'),
  lambShoulder: img('lamb-shoulder.jpg'),
  lambChops: img('lamb-chops.jpg'),
  lambMince: img('lamb-mince.jpg'),
  goatMeat: img('goat-meat.jpg'),
  beef: img('beef.jpg'),
  beefCurry: img('beef-curry.jpg'),
  beefKeema: img('beef-keema.jpg'),
  beefSteak: img('beef-steak.jpg'),
  beefBoneless: img('beef-boneless.jpg'),
  beefRibs: img('beef-ribs.jpg'),
  fish: img('fish.jpg'),
  fishHilsa: img('fish-hilsa.jpg'),
  fishRohu: img('fish-rohu.jpg'),
  fishPomfret: img('fish-pomfret.jpg'),
  fishSalmon: img('fish-salmon.jpg'),
  fishPrawns: img('fish-prawns.jpg'),
  eggplant: img('eggplant.jpg'),
  okra: img('okra.jpg'),
  bottleGourd: img('bottleGourd.jpg'),
  bitterGourd: img('bitterGourd.jpg'),
  tomato: img('tomato.jpg'),
  potato: img('potato.jpg'),
  greens: img('spinach.jpg'),
  methi: img('methi.jpg'),
  coriander: img('coriander.jpg'),
  onion: img('onion.jpg'),
  garlic: img('garlic.jpg'),
  ginger: img('ginger.jpg'),
  yoghurt: img('yoghurt.jpg'),
  bengaliDoi: img('bengali-doi.jpg'),
  labneh: img('labneh.jpg'),
  cheese: img('paneer.jpg'),
  eggs: img('eggs.jpg'),
  brownEggs: img('brown-eggs.jpg'),
  organicEggs: img('organic-eggs.jpg'),
  assamTea: img('assam-tea.jpg'),
  kenyanTea: img('kenyan-tea.jpg'),
  masalaChai: img('masala-chai.jpg'),
  greenTea: img('green-tea.jpg'),
  ceylonTea: img('ceylon-tea.jpg'),
  arabicCoffee: img('arabic-coffee.jpg'),
  turkishCoffee: img('turkish-coffee.jpg'),
  instantCoffee: img('instant-coffee.jpg'),
  cardamomCoffee: img('cardamom-coffee.jpg'),
  espressoCoffee: img('espresso-coffee.jpg'),
  medjoolDates: img('medjool-dates.jpg'),
  ajwaDates: img('ajwa-dates.jpg'),
  freshDates: img('fresh-dates.jpg'),
  plainNaan: img('plain-naan.jpg'),
  chapati: img('chapati.jpg'),
  garlicNaan: img('garlic-naan.jpg'),
  pita: img('pita.jpg'),
  baklava: img('baklava.jpg'),
  jaggery: img('jaggery.jpg'),
  gulabJamun: img('gulab-jamun.jpg'),
  pickle: img('pickle.jpg'),
  mixedPickle: img('mixed-pickle.jpg'),
  tamarindPaste: img('tamarind-paste.jpg'),
  tahini: img('tahini.jpg'),
  juice: img('juice.jpg'),
  lemonSquash: img('lemon-squash.jpg'),
  roseSyrup: img('rose-syrup.jpg'),
  roohAfza: img('rooh-afza.jpg'),
  roseWater: img('rose-water.jpg'),
  orangeBlossom: img('orange-blossom.jpg'),
  mango: img('mango.jpg'),
  mint: img('mint.jpg'),
  banana: img('banana.jpg'),
  apple: img('apple.jpg'),
  laundryDetergent: img('laundry-detergent.jpg'),
  laundryLiquid: img('laundry-liquid.jpg'),
  fabricSoftener: img('fabric-softener.jpg'),
  stainRemover: img('stain-remover.jpg'),
  washingPowder: img('washing-powder.jpg'),
  pomegranate: img('pomegranate.jpg'),
  lettuce: img('lettuce.jpg'),
  greenBeans: img('greenBeans.jpg'),
  orangeJuice: img('orangeJuice.jpg'),
  coconutMilk: img('coconut-milk.jpg'),
} as const;

function p(
  partial: Omit<CulturalProductSeed, 'imageUrl'> & { image: keyof typeof IMG },
): CulturalProductSeed {
  const { image, ...rest } = partial;
  return { ...rest, imageUrl: IMG[image] };
}

/**
 * Curated ~100 SKUs. Barcodes use 8902… series (distinct from demo 8901…).
 * Pack / colour / form differences are separate rows (Option 1).
 */
export const CULTURAL_PRODUCT_BANK: CulturalProductSeed[] = [
  // —— Rice & grains ——
  p({
    name: 'Basmati Rice 1kg',
    slug: 'basmati-rice-1kg',
    barcode: '8902001000001',
    sku: 'SKU-BAS-1',
    description: 'Premium aged long-grain basmati for everyday pulao and biryani.',
    category: 'Pantry',
    price: 3.49,
    tags: ['india', 'pakistan', 'bangladesh', 'rice', 'pantry'],
    image: 'basmati',
  }),
  p({
    name: 'Basmati Rice 5kg',
    slug: 'basmati-rice-5kg',
    barcode: '8901001000001',
    sku: 'SKU-RICE-5',
    description: 'Premium long grain basmati — family pack.',
    category: 'Pantry',
    price: 12.99,
    tags: ['india', 'pakistan', 'bangladesh', 'rice', 'pantry'],
    image: 'basmati',
  }),
  p({
    name: 'Basmati Rice 10kg',
    slug: 'basmati-rice-10kg',
    barcode: '8902001000002',
    sku: 'SKU-BAS-10',
    description: 'Bulk aged basmati for large family kitchens.',
    category: 'Pantry',
    price: 23.99,
    tags: ['india', 'pakistan', 'bangladesh', 'rice', 'pantry'],
    image: 'basmati',
  }),
  p({
    name: 'Sella Basmati Rice 5kg',
    slug: 'sella-basmati-rice-5kg',
    barcode: '8902001000003',
    sku: 'SKU-SELLA-5',
    description: 'Parboiled sella basmati — fluffy grains, biryani favourite.',
    category: 'Pantry',
    price: 13.49,
    tags: ['pakistan', 'india', 'rice', 'pantry'],
    image: 'sellaRice',
  }),
  p({
    name: 'Jeera Rice 1kg',
    slug: 'jeera-rice-1kg',
    barcode: '8902001000004',
    sku: 'SKU-JEERA-1',
    description: 'Short-grain jeera / kalijeera style rice for Bengali and Bangla kitchens.',
    category: 'Pantry',
    price: 2.99,
    tags: ['bangladesh', 'india', 'rice', 'pantry'],
    image: 'jeeraRice',
  }),
  p({
    name: 'Broken Basmati Rice 5kg',
    slug: 'broken-basmati-rice-5kg',
    barcode: '8902001000005',
    sku: 'SKU-BRICE-5',
    description: 'Economical broken basmati for khichdi, payesh, and everyday meals.',
    category: 'Pantry',
    price: 8.99,
    tags: ['bangladesh', 'india', 'pakistan', 'rice', 'pantry'],
    image: 'brokenRice',
  }),
  p({
    name: 'Bulgur Wheat 1kg',
    slug: 'bulgur-wheat-1kg',
    barcode: '8902001000006',
    sku: 'SKU-BULGUR-1',
    description: 'Fine bulgur for tabbouleh, pilafs, and Levantine sides.',
    category: 'Pantry',
    price: 3.29,
    tags: ['arabic', 'grains', 'pantry'],
    image: 'bulgur',
  }),
  p({
    name: 'Freekeh 500g',
    slug: 'freekeh-500g',
    barcode: '8902001000007',
    sku: 'SKU-FREEKEH-500',
    description: 'Roasted green wheat — classic Arabic grain.',
    category: 'Pantry',
    price: 4.49,
    tags: ['arabic', 'grains', 'pantry'],
    image: 'freekeh',
  }),
  p({
    name: 'Couscous 1kg',
    slug: 'couscous-1kg',
    barcode: '8902001000008',
    sku: 'SKU-COUS-1',
    description: 'Medium couscous for stews and Maghrebi plates.',
    category: 'Pantry',
    price: 2.79,
    tags: ['arabic', 'grains', 'pantry'],
    image: 'couscous',
  }),

  // —— Dals & pulses ——
  p({
    name: 'Toor Dal 1kg',
    slug: 'toor-dal-1kg',
    barcode: '8902001000010',
    sku: 'SKU-TOOR-1',
    description: 'Split pigeon peas — everyday Indian and Pakistani daal.',
    category: 'Pantry',
    price: 2.89,
    tags: ['india', 'pakistan', 'dal', 'pantry'],
    image: 'toorDal',
  }),
  p({
    name: 'Toor Dal 5kg',
    slug: 'toor-dal-5kg',
    barcode: '8902001000011',
    sku: 'SKU-TOOR-5',
    description: 'Family pack split pigeon peas.',
    category: 'Pantry',
    price: 12.49,
    tags: ['india', 'pakistan', 'dal', 'pantry'],
    image: 'toorDal',
  }),
  p({
    name: 'Masoor Dal 1kg',
    slug: 'masoor-dal-1kg',
    barcode: '8902001000012',
    sku: 'SKU-MASOOR-1',
    description: 'Red lentils — quick-cook daal across South Asia.',
    category: 'Pantry',
    price: 2.59,
    tags: ['india', 'pakistan', 'bangladesh', 'dal', 'pantry'],
    image: 'masoorDal',
  }),
  p({
    name: 'Moong Dal 1kg',
    slug: 'moong-dal-1kg',
    barcode: '8902001000013',
    sku: 'SKU-MOONG-1',
    description: 'Split yellow mung — light khichdi and Bengali moong daal.',
    category: 'Pantry',
    price: 2.79,
    tags: ['india', 'bangladesh', 'pakistan', 'dal', 'pantry'],
    image: 'moongDal',
  }),
  p({
    name: 'Chana Dal 1kg',
    slug: 'chana-dal-1kg',
    barcode: '8902001000014',
    sku: 'SKU-CHANA-1',
    description: 'Split chickpeas for stews, snacks, and bhaja.',
    category: 'Pantry',
    price: 2.69,
    tags: ['india', 'bangladesh', 'pakistan', 'dal', 'pantry'],
    image: 'chanaDal',
  }),
  p({
    name: 'Urad Dal 1kg',
    slug: 'urad-dal-1kg',
    barcode: '8902001000015',
    sku: 'SKU-URAD-1',
    description: 'Black gram — dosa, idli, and Punjabi daal makhani base.',
    category: 'Pantry',
    price: 3.19,
    tags: ['india', 'pakistan', 'dal', 'pantry'],
    image: 'uradDal',
  }),
  p({
    name: 'Whole Chickpeas 1kg',
    slug: 'whole-chickpeas-1kg',
    barcode: '8902001000016',
    sku: 'SKU-CHICKPEA-1',
    description: 'Dried chickpeas for chana masala, hummus, and chole.',
    category: 'Pantry',
    price: 2.49,
    tags: ['india', 'pakistan', 'arabic', 'pulses', 'pantry'],
    image: 'chickpeas',
  }),
  p({
    name: 'Whole Moong 1kg',
    slug: 'whole-moong-1kg',
    barcode: '8902001000017',
    sku: 'SKU-WMOONG-1',
    description: 'Whole green mung beans for sprouting and hearty daal.',
    category: 'Pantry',
    price: 2.99,
    tags: ['india', 'bangladesh', 'dal', 'pantry'],
    image: 'wholeMoong',
  }),
  p({
    name: 'Dried Fava Beans 1kg',
    slug: 'dried-fava-beans-1kg',
    barcode: '8902001000018',
    sku: 'SKU-FAVA-1',
    description: 'Ful medames staple — Egyptian and Levantine classic.',
    category: 'Pantry',
    price: 3.09,
    tags: ['arabic', 'pulses', 'pantry'],
    image: 'favaBeans',
  }),
  p({
    name: 'Red Kidney Beans 1kg',
    slug: 'red-kidney-beans-1kg',
    barcode: '8902001000019',
    sku: 'SKU-RAJMA-1',
    description: 'Rajma beans for Punjabi-style curry.',
    category: 'Pantry',
    price: 2.89,
    tags: ['india', 'pakistan', 'pulses', 'pantry'],
    image: 'kidneyBeans',
  }),

  // —— Flour & atta ——
  p({
    name: 'Chakki Atta 5kg',
    slug: 'chakki-atta-5kg',
    barcode: '8902001000020',
    sku: 'SKU-ATTA-5',
    description: 'Stone-ground whole wheat flour for roti and chapati.',
    category: 'Pantry',
    price: 7.99,
    tags: ['india', 'pakistan', 'bangladesh', 'flour', 'pantry'],
    image: 'flour',
  }),
  p({
    name: 'Chakki Atta 10kg',
    slug: 'chakki-atta-10kg',
    barcode: '8902001000021',
    sku: 'SKU-ATTA-10',
    description: 'Family pack chakki atta.',
    category: 'Pantry',
    price: 14.49,
    tags: ['india', 'pakistan', 'bangladesh', 'flour', 'pantry'],
    image: 'flour',
  }),
  p({
    name: 'Besan (Gram Flour) 1kg',
    slug: 'besan-gram-flour-1kg',
    barcode: '8902001000022',
    sku: 'SKU-BESAN-1',
    description: 'Chickpea flour for pakora, bhaji, and sweets.',
    category: 'Pantry',
    price: 2.99,
    tags: ['india', 'pakistan', 'bangladesh', 'flour', 'pantry'],
    image: 'besan',
  }),
  p({
    name: 'Rice Flour 1kg',
    slug: 'rice-flour-1kg',
    barcode: '8902001000023',
    sku: 'SKU-RFLOUR-1',
    description: 'Fine rice flour for sweets, snacks, and gluten-free batter.',
    category: 'Pantry',
    price: 2.49,
    tags: ['india', 'bangladesh', 'flour', 'pantry'],
    image: 'riceFlour',
  }),
  p({
    name: 'Suji / Semolina 1kg',
    slug: 'suji-semolina-1kg',
    barcode: '8902001000024',
    sku: 'SKU-SUJI-1',
    description: 'Coarse semolina for halwa, upma, and rava dosa.',
    category: 'Pantry',
    price: 2.29,
    tags: ['india', 'pakistan', 'bangladesh', 'flour', 'pantry'],
    image: 'suji',
  }),
  p({
    name: 'Cornflour 500g',
    slug: 'cornflour-500g',
    barcode: '8902001000025',
    sku: 'SKU-CORN-500',
    description: 'Corn starch for thickening curries and gravies.',
    category: 'Pantry',
    price: 1.79,
    tags: ['india', 'pakistan', 'pantry'],
    image: 'cornflour',
  }),

  // —— Spices ——
  p({
    name: 'Turmeric Powder 200g',
    slug: 'turmeric-powder-200g',
    barcode: '8902001000030',
    sku: 'SKU-HALDI-200',
    description: 'Bright ground turmeric for curries and marinades.',
    category: 'Pantry',
    price: 1.99,
    tags: ['india', 'pakistan', 'bangladesh', 'spice', 'pantry'],
    image: 'turmeric',
  }),
  p({
    name: 'Cumin Seeds 200g',
    slug: 'cumin-seeds-200g',
    barcode: '8902001000031',
    sku: 'SKU-JEERA-SEED-200',
    description: 'Whole jeera for tempering and spice blends.',
    category: 'Pantry',
    price: 2.29,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'spice', 'pantry'],
    image: 'cumin',
  }),
  p({
    name: 'Coriander Powder 200g',
    slug: 'coriander-powder-200g',
    barcode: '8902001000032',
    sku: 'SKU-DHANIA-200',
    description: 'Ground coriander — base of South Asian spice mixes.',
    category: 'Pantry',
    price: 1.89,
    tags: ['india', 'pakistan', 'bangladesh', 'spice', 'pantry'],
    image: 'corianderPowder',
  }),
  p({
    name: 'Red Chilli Powder 200g',
    slug: 'red-chilli-powder-200g',
    barcode: '8902001000033',
    sku: 'SKU-CHILLI-200',
    description: 'Hot ground chilli for everyday cooking.',
    category: 'Pantry',
    price: 2.19,
    tags: ['india', 'pakistan', 'bangladesh', 'spice', 'pantry'],
    image: 'chilli',
  }),
  p({
    name: 'Kashmiri Chilli Powder 200g',
    slug: 'kashmiri-chilli-powder-200g',
    barcode: '8902001000034',
    sku: 'SKU-KASH-200',
    description: 'Mild, deep-red Kashmiri chilli for colour without extreme heat.',
    category: 'Pantry',
    price: 2.79,
    tags: ['india', 'pakistan', 'spice', 'pantry'],
    image: 'kashmiriChilli',
  }),
  p({
    name: 'Garam Masala 100g',
    slug: 'garam-masala-100g',
    barcode: '8902001000035',
    sku: 'SKU-GARAM-100',
    description: 'Warm finishing blend for North Indian and Pakistani curries.',
    category: 'Pantry',
    price: 2.49,
    tags: ['india', 'pakistan', 'spice', 'pantry'],
    image: 'garamMasala',
  }),
  p({
    name: 'Biryani Masala 100g',
    slug: 'biryani-masala-100g',
    barcode: '8902001000036',
    sku: 'SKU-BIRY-100',
    description: 'Ready biryani spice mix for layered rice dishes.',
    category: 'Pantry',
    price: 2.99,
    tags: ['india', 'pakistan', 'bangladesh', 'spice', 'pantry'],
    image: 'biryaniMasala',
  }),
  p({
    name: 'Mustard Seeds 200g',
    slug: 'mustard-seeds-200g',
    barcode: '8902001000037',
    sku: 'SKU-MUSTARD-200',
    description: 'Black mustard seeds for Bengali and South Indian tempering.',
    category: 'Pantry',
    price: 1.99,
    tags: ['bangladesh', 'india', 'spice', 'pantry'],
    image: 'mustardSeeds',
  }),
  p({
    name: 'Fenugreek Seeds 200g',
    slug: 'fenugreek-seeds-200g',
    barcode: '8902001000038',
    sku: 'SKU-METHI-200',
    description: 'Methi seeds for pickles, dals, and spice blends.',
    category: 'Pantry',
    price: 1.89,
    tags: ['india', 'pakistan', 'bangladesh', 'spice', 'pantry'],
    image: 'fenugreekSeeds',
  }),
  p({
    name: 'Green Cardamom 50g',
    slug: 'green-cardamom-50g',
    barcode: '8902001000039',
    sku: 'SKU-ELAICHI-50',
    description: 'Whole green cardamom pods for tea, sweets, and rice.',
    category: 'Pantry',
    price: 4.99,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'spice', 'pantry'],
    image: 'cardamom',
  }),
  p({
    name: 'Cloves 50g',
    slug: 'cloves-50g',
    barcode: '8902001000040',
    sku: 'SKU-CLOVE-50',
    description: 'Whole cloves for garam masala and Arabic rice.',
    category: 'Pantry',
    price: 2.49,
    tags: ['india', 'pakistan', 'arabic', 'spice', 'pantry'],
    image: 'cloves',
  }),
  p({
    name: 'Cinnamon Sticks 50g',
    slug: 'cinnamon-sticks-50g',
    barcode: '8902001000041',
    sku: 'SKU-CINN-50',
    description: 'Cassia cinnamon quills for curries and desserts.',
    category: 'Pantry',
    price: 2.29,
    tags: ['india', 'pakistan', 'arabic', 'spice', 'pantry'],
    image: 'cinnamon',
  }),
  p({
    name: 'Black Peppercorns 100g',
    slug: 'black-peppercorns-100g',
    barcode: '8902001000042',
    sku: 'SKU-PEPPER-100',
    description: 'Whole black pepper for fresh grinding.',
    category: 'Pantry',
    price: 2.99,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'spice', 'pantry'],
    image: 'blackPepper',
  }),
  p({
    name: 'Bay Leaves 20g',
    slug: 'bay-leaves-20g',
    barcode: '8902001000043',
    sku: 'SKU-BAY-20',
    description: 'Dried bay leaves for rice and stews.',
    category: 'Pantry',
    price: 1.49,
    tags: ['india', 'pakistan', 'arabic', 'spice', 'pantry'],
    image: 'bayLeaves',
  }),
  p({
    name: 'Zaatar Blend 200g',
    slug: 'zaatar-blend-200g',
    barcode: '8902001000044',
    sku: 'SKU-ZAATAR-200',
    description: 'Classic Levantine zaatar with thyme, sesame, and sumac.',
    category: 'Pantry',
    price: 3.99,
    tags: ['arabic', 'spice', 'pantry'],
    image: 'zaatar',
  }),
  p({
    name: 'Sumac 100g',
    slug: 'sumac-100g',
    barcode: '8902001000045',
    sku: 'SKU-SUMAC-100',
    description: 'Tangy ground sumac for salads and grilled meats.',
    category: 'Pantry',
    price: 2.79,
    tags: ['arabic', 'spice', 'pantry'],
    image: 'sumac',
  }),
  p({
    name: 'Baharat Spice Mix 100g',
    slug: 'baharat-spice-mix-100g',
    barcode: '8902001000046',
    sku: 'SKU-BAHARAT-100',
    description: 'Warm Arabic seven-spice style blend.',
    category: 'Pantry',
    price: 3.29,
    tags: ['arabic', 'spice', 'pantry'],
    image: 'baharat',
  }),
  p({
    name: 'Panch Phoron 100g',
    slug: 'panch-phoron-100g',
    barcode: '8902001000047',
    sku: 'SKU-PANCH-100',
    description: 'Bengali five-spice mix for fish and vegetable dishes.',
    category: 'Pantry',
    price: 2.19,
    tags: ['bangladesh', 'india', 'spice', 'pantry'],
    image: 'panchPhoron',
  }),

  // —— Oils & fats ——
  p({
    name: 'Mustard Oil 1L',
    slug: 'mustard-oil-1l',
    barcode: '8902001000050',
    sku: 'SKU-MUSTOIL-1',
    description: 'Pungent mustard oil for Bengali and North Indian cooking.',
    category: 'Pantry',
    price: 5.99,
    tags: ['bangladesh', 'india', 'oil', 'pantry'],
    image: 'oil',
  }),
  p({
    name: 'Mustard Oil 500ml',
    slug: 'mustard-oil-500ml',
    barcode: '8902001000051',
    sku: 'SKU-MUSTOIL-500',
    description: 'Half-litre mustard oil.',
    category: 'Pantry',
    price: 3.49,
    tags: ['bangladesh', 'india', 'oil', 'pantry'],
    image: 'oil',
  }),
  p({
    name: 'Sunflower Oil 2L',
    slug: 'sunflower-oil-2l',
    barcode: '8902001000052',
    sku: 'SKU-SUNOIL-2',
    description: 'Neutral cooking oil for frying and everyday use.',
    category: 'Pantry',
    price: 4.99,
    tags: ['india', 'pakistan', 'bangladesh', 'oil', 'pantry'],
    image: 'sunflowerOil',
  }),
  p({
    name: 'Olive Oil 1L',
    slug: 'olive-oil-1l',
    barcode: '8901001000003',
    sku: 'SKU-OIL-1',
    description: 'Extra virgin olive oil for Arabic and Mediterranean cooking.',
    category: 'Pantry',
    price: 6.75,
    tags: ['arabic', 'oil', 'pantry'],
    image: 'oliveOil',
  }),
  p({
    name: 'Pure Desi Ghee 1kg',
    slug: 'pure-desi-ghee-1kg',
    barcode: '8902001000053',
    sku: 'SKU-GHEE-1',
    description: 'Clarified butter for roti, sweets, and rich curries.',
    category: 'Pantry',
    price: 11.99,
    tags: ['india', 'pakistan', 'bangladesh', 'dairy', 'pantry'],
    image: 'ghee',
  }),
  p({
    name: 'Pure Desi Ghee 500g',
    slug: 'pure-desi-ghee-500g',
    barcode: '8902001000054',
    sku: 'SKU-GHEE-500',
    description: 'Half-kilo desi ghee.',
    category: 'Pantry',
    price: 6.49,
    tags: ['india', 'pakistan', 'bangladesh', 'dairy', 'pantry'],
    image: 'ghee',
  }),
  p({
    name: 'Tahini 400g',
    slug: 'tahini-400g',
    barcode: '8902001000055',
    sku: 'SKU-TAHINI-400',
    description: 'Sesame paste for hummus, sauces, and Levantine dishes.',
    category: 'Pantry',
    price: 4.29,
    tags: ['arabic', 'pantry'],
    image: 'tahini',
  }),

  // —— Meat & poultry ——
  p({
    name: 'Chicken Thighs 1kg',
    slug: 'chicken-thighs-1kg',
    barcode: '8901001000002',
    sku: 'SKU-CHICK-1',
    description: 'Halal chicken thighs.',
    category: 'Meat & Poultry',
    price: 8.5,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'chicken', 'meat'],
    image: 'chickenThighs',
  }),
  p({
    name: 'Whole Chicken 1.5kg',
    slug: 'whole-chicken-1-5kg',
    barcode: '8902001000060',
    sku: 'SKU-WCHICK-15',
    description: 'Halal whole chicken for roasting or curry cuts.',
    category: 'Meat & Poultry',
    price: 9.99,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'chicken', 'meat'],
    image: 'chickenWhole',
  }),
  p({
    name: 'Chicken Breast 1kg',
    slug: 'chicken-breast-1kg',
    barcode: '8902001000061',
    sku: 'SKU-CBREAST-1',
    description: 'Boneless halal chicken breast.',
    category: 'Meat & Poultry',
    price: 10.49,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'chicken', 'meat'],
    image: 'chickenBreast',
  }),
  p({
    name: 'Chicken Keema 500g',
    slug: 'chicken-keema-500g',
    barcode: '8902001000062',
    sku: 'SKU-CKEEMA-500',
    description: 'Halal minced chicken for keema curry and kebabs.',
    category: 'Meat & Poultry',
    price: 5.49,
    tags: ['india', 'pakistan', 'bangladesh', 'chicken', 'meat'],
    image: 'chickenKeema',
  }),
  p({
    name: 'Mutton Curry Pieces 1kg',
    slug: 'mutton-curry-pieces-1kg',
    barcode: '8902001000063',
    sku: 'SKU-MUTTON-1',
    description: 'Halal goat/mutton bone-in curry cuts.',
    category: 'Meat & Poultry',
    price: 14.99,
    tags: ['india', 'pakistan', 'bangladesh', 'lamb', 'meat'],
    image: 'lambMutton',
  }),
  p({
    name: 'Lamb Shoulder 1kg',
    slug: 'lamb-shoulder-1kg',
    barcode: '8902001000064',
    sku: 'SKU-LAMB-1',
    description: 'Halal lamb shoulder for Mandi, stews, and grills.',
    category: 'Meat & Poultry',
    price: 15.99,
    tags: ['arabic', 'pakistan', 'lamb', 'meat'],
    image: 'lambShoulder',
  }),
  p({
    name: 'Beef Curry Pieces 1kg',
    slug: 'beef-curry-pieces-1kg',
    barcode: '8902001000065',
    sku: 'SKU-BEEF-1',
    description: 'Halal beef bone-in pieces for Bengali and Pakistani beef curry.',
    category: 'Meat & Poultry',
    price: 12.99,
    tags: ['bangladesh', 'pakistan', 'beef', 'meat'],
    image: 'beefCurry',
  }),
  p({
    name: 'Beef Keema 500g',
    slug: 'beef-keema-500g',
    barcode: '8902001000066',
    sku: 'SKU-BKEEMA-500',
    description: 'Halal minced beef.',
    category: 'Meat & Poultry',
    price: 6.49,
    tags: ['pakistan', 'bangladesh', 'india', 'beef', 'meat'],
    image: 'beefKeema',
  }),
  p({
    name: 'Hilsa (Ilish) Steaks 500g',
    slug: 'hilsa-ilish-steaks-500g',
    barcode: '8902001000067',
    sku: 'SKU-HILSA-500',
    description: 'Frozen hilsa steaks — Bengali celebration fish.',
    category: 'Meat & Poultry',
    price: 16.99,
    tags: ['bangladesh', 'fish', 'meat'],
    image: 'fishHilsa',
  }),
  p({
    name: 'Rohu Fish Steaks 1kg',
    slug: 'rohu-fish-steaks-1kg',
    barcode: '8902001000068',
    sku: 'SKU-ROHU-1',
    description: 'Freshwater rohu steaks for Bengali fish curry.',
    category: 'Meat & Poultry',
    price: 11.49,
    tags: ['bangladesh', 'india', 'fish', 'meat'],
    image: 'fishRohu',
  }),

  // —— Produce (fixed packs) ——
  p({
    name: 'Brown Onions 1kg',
    slug: 'brown-onions-1kg',
    barcode: '8902001000070',
    sku: 'SKU-ONION-1',
    description: 'Everyday cooking onions.',
    category: 'Produce',
    price: 1.49,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'produce'],
    image: 'onion',
  }),
  p({
    name: 'Garlic 500g',
    slug: 'garlic-500g',
    barcode: '8902001000071',
    sku: 'SKU-GARLIC-500',
    description: 'Fresh garlic bulbs.',
    category: 'Produce',
    price: 2.29,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'produce'],
    image: 'garlic',
  }),
  p({
    name: 'Fresh Ginger 500g',
    slug: 'fresh-ginger-500g',
    barcode: '8902001000072',
    sku: 'SKU-GINGER-500',
    description: 'Fresh ginger root for pastes and teas.',
    category: 'Produce',
    price: 2.49,
    tags: ['india', 'pakistan', 'bangladesh', 'produce'],
    image: 'ginger',
  }),
  p({
    name: 'Green Chillies 200g',
    slug: 'green-chillies-200g',
    barcode: '8902001000073',
    sku: 'SKU-GCHILLI-200',
    description: 'Hot green chillies for tempering and chutneys.',
    category: 'Produce',
    price: 1.29,
    tags: ['india', 'pakistan', 'bangladesh', 'produce'],
    image: 'greenChilli',
  }),
  p({
    name: 'Coriander Bunch 100g',
    slug: 'coriander-bunch-100g',
    barcode: '8902001000074',
    sku: 'SKU-CORI-100',
    description: 'Fresh coriander leaves (dhania).',
    category: 'Produce',
    price: 0.99,
    tags: ['india', 'pakistan', 'bangladesh', 'produce'],
    image: 'coriander',
  }),
  p({
    name: 'Baby Spinach 200g',
    slug: 'baby-spinach-200g',
    barcode: '8902001000075',
    sku: 'SKU-SPIN-200',
    description: 'Fresh spinach for saag and salads.',
    category: 'Produce',
    price: 1.79,
    tags: ['india', 'pakistan', 'arabic', 'produce'],
    image: 'greens',
  }),
  p({
    name: 'Okra (Bhindi) 500g',
    slug: 'okra-bhindi-500g',
    barcode: '8902001000076',
    sku: 'SKU-OKRA-500',
    description: 'Fresh okra for bhindi masala and Bengali dherosh.',
    category: 'Produce',
    price: 2.49,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'produce'],
    image: 'okra',
  }),
  p({
    name: 'Aubergine 500g',
    slug: 'aubergine-500g',
    barcode: '8902001000077',
    sku: 'SKU-BAINGAN-500',
    description: 'Aubergine / brinjal for baingan bharta and begun bhaja.',
    category: 'Produce',
    price: 1.99,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'produce'],
    image: 'eggplant',
  }),
  p({
    name: 'Bottle Gourd 1kg',
    slug: 'bottle-gourd-1kg',
    barcode: '8902001000078',
    sku: 'SKU-LAUKI-1',
    description: 'Lauki / lau — mild gourd for dals and curries.',
    category: 'Produce',
    price: 2.29,
    tags: ['india', 'pakistan', 'bangladesh', 'produce'],
    image: 'bottleGourd',
  }),
  p({
    name: 'Bitter Gourd 500g',
    slug: 'bitter-gourd-500g',
    barcode: '8902001000079',
    sku: 'SKU-KARELA-500',
    description: 'Karela / korola for traditional bitter vegetable dishes.',
    category: 'Produce',
    price: 2.19,
    tags: ['india', 'bangladesh', 'produce'],
    image: 'bitterGourd',
  }),
  p({
    name: 'Tomatoes 1kg',
    slug: 'tomatoes-1kg',
    barcode: '8902001000080',
    sku: 'SKU-TOMATO-1',
    description: 'Ripe tomatoes for curries and salads.',
    category: 'Produce',
    price: 2.49,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'produce'],
    image: 'tomato',
  }),
  p({
    name: 'Potatoes 2kg',
    slug: 'potatoes-2kg',
    barcode: '8902001000081',
    sku: 'SKU-POTATO-2',
    description: 'Cooking potatoes for aloo dishes and sides.',
    category: 'Produce',
    price: 2.99,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'produce'],
    image: 'potato',
  }),

  // —— Dairy & eggs ——
  p({
    name: 'Natural Yoghurt 1kg',
    slug: 'natural-yoghurt-1kg',
    barcode: '8902001000090',
    sku: 'SKU-YOG-1',
    description: 'Thick natural yoghurt for raita, lassi, and marinades.',
    category: 'Dairy & Eggs',
    price: 2.49,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'dairy'],
    image: 'yoghurt',
  }),
  p({
    name: 'Bengali Doi 500g',
    slug: 'bengali-doi-500g',
    barcode: '8902001000091',
    sku: 'SKU-DOI-500',
    description: 'Set sweet-style Bengali doi yoghurt.',
    category: 'Dairy & Eggs',
    price: 2.29,
    tags: ['bangladesh', 'dairy'],
    image: 'bengaliDoi',
  }),
  p({
    name: 'Paneer 250g',
    slug: 'paneer-250g',
    barcode: '8902001000092',
    sku: 'SKU-PANEER-250',
    description: 'Fresh Indian cottage cheese block.',
    category: 'Dairy & Eggs',
    price: 3.49,
    tags: ['india', 'pakistan', 'dairy'],
    image: 'cheese',
  }),
  p({
    name: 'Paneer 500g',
    slug: 'paneer-500g',
    barcode: '8902001000093',
    sku: 'SKU-PANEER-500',
    description: 'Family pack fresh paneer.',
    category: 'Dairy & Eggs',
    price: 5.99,
    tags: ['india', 'pakistan', 'dairy'],
    image: 'cheese',
  }),
  p({
    name: 'Labneh 400g',
    slug: 'labneh-400g',
    barcode: '8902001000094',
    sku: 'SKU-LABNEH-400',
    description: 'Strained yoghurt cheese — Levantine staple.',
    category: 'Dairy & Eggs',
    price: 3.79,
    tags: ['arabic', 'dairy'],
    image: 'labneh',
  }),
  p({
    name: 'Free Range Eggs (12)',
    slug: 'free-range-eggs-12',
    barcode: '8902001000095',
    sku: 'SKU-EGGS-12',
    description: 'Box of 12 free-range eggs.',
    category: 'Dairy & Eggs',
    price: 3.99,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'eggs'],
    image: 'eggs',
  }),

  // —— Beverages ——
  p({
    name: 'Assam Tea 450g',
    slug: 'assam-tea-450g',
    barcode: '8902001000100',
    sku: 'SKU-TEA-450',
    description: 'Strong Assam leaf tea for chai.',
    category: 'Beverages',
    price: 4.49,
    tags: ['india', 'bangladesh', 'tea', 'beverages'],
    image: 'assamTea',
  }),
  p({
    name: 'Kenyan Dust Tea 450g',
    slug: 'kenyan-dust-tea-450g',
    barcode: '8902001000101',
    sku: 'SKU-TEADUST-450',
    description: 'Fine tea dust popular in Pakistani and Bengali chai.',
    category: 'Beverages',
    price: 3.99,
    tags: ['pakistan', 'bangladesh', 'tea', 'beverages'],
    image: 'kenyanTea',
  }),
  p({
    name: 'Arabic Coffee (Qahwa) 250g',
    slug: 'arabic-coffee-qahwa-250g',
    barcode: '8902001000102',
    sku: 'SKU-QAHWA-250',
    description: 'Light roasted Arabic coffee with cardamom notes.',
    category: 'Beverages',
    price: 6.99,
    tags: ['arabic', 'coffee', 'beverages'],
    image: 'arabicCoffee',
  }),
  p({
    name: 'Mango Juice 1L',
    slug: 'mango-juice-1l',
    barcode: '8902001000103',
    sku: 'SKU-MANGO-1',
    description: 'Sweet mango drink — South Asian favourite.',
    category: 'Beverages',
    price: 2.49,
    tags: ['india', 'pakistan', 'bangladesh', 'beverages'],
    image: 'juice',
  }),
  p({
    name: 'Rose Syrup 500ml',
    slug: 'rose-syrup-500ml',
    barcode: '8902001000104',
    sku: 'SKU-ROSE-500',
    description: 'Rose sharbat syrup for drinks and desserts.',
    category: 'Beverages',
    price: 3.29,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'beverages'],
    image: 'roseSyrup',
  }),
  p({
    name: 'Rooh Afza Style Squash 800ml',
    slug: 'rooh-afza-style-squash-800ml',
    barcode: '8902001000105',
    sku: 'SKU-ROOH-800',
    description: 'Floral concentrate squash for summer drinks.',
    category: 'Beverages',
    price: 4.49,
    tags: ['pakistan', 'india', 'bangladesh', 'beverages'],
    image: 'roohAfza',
  }),

  // —— Bakery, sweets, condiments ——
  p({
    name: 'Pita Bread (6 pack)',
    slug: 'pita-bread-6-pack',
    barcode: '8902001000110',
    sku: 'SKU-PITA-6',
    description: 'Soft pita pockets for wraps and dips.',
    category: 'Pantry',
    price: 1.99,
    tags: ['arabic', 'bread', 'pantry'],
    image: 'pita',
  }),
  p({
    name: 'Plain Naan (4 pack)',
    slug: 'plain-naan-4-pack',
    barcode: '8902001000111',
    sku: 'SKU-NAAN-4',
    description: 'Ready-to-heat plain naan breads.',
    category: 'Pantry',
    price: 2.49,
    tags: ['india', 'pakistan', 'bread', 'pantry'],
    image: 'plainNaan',
  }),
  p({
    name: 'Medjool Dates 500g',
    slug: 'medjool-dates-500g',
    barcode: '8902001000112',
    sku: 'SKU-MEDJ-500',
    description: 'Soft Medjool dates — Ramadan and Arabic table staple.',
    category: 'Pantry',
    price: 6.99,
    tags: ['arabic', 'dates', 'pantry'],
    image: 'medjoolDates',
  }),
  p({
    name: 'Ajwa Dates 400g',
    slug: 'ajwa-dates-400g',
    barcode: '8902001000113',
    sku: 'SKU-AJWA-400',
    description: 'Premium Ajwa dates from Medina tradition.',
    category: 'Pantry',
    price: 9.99,
    tags: ['arabic', 'dates', 'pantry'],
    image: 'ajwaDates',
  }),
  p({
    name: 'Jaggery (Gur) 500g',
    slug: 'jaggery-gur-500g',
    barcode: '8902001000114',
    sku: 'SKU-GUR-500',
    description: 'Natural cane jaggery for sweets and winter drinks.',
    category: 'Pantry',
    price: 2.79,
    tags: ['india', 'pakistan', 'bangladesh', 'sweets', 'pantry'],
    image: 'jaggery',
  }),
  p({
    name: 'Gulab Jamun Mix 500g',
    slug: 'gulab-jamun-mix-500g',
    barcode: '8902001000115',
    sku: 'SKU-GULAB-500',
    description: 'Instant mix for classic gulab jamun sweets.',
    category: 'Pantry',
    price: 3.49,
    tags: ['india', 'pakistan', 'bangladesh', 'sweets', 'pantry'],
    image: 'gulabJamun',
  }),
  p({
    name: 'Baklava Assortment 250g',
    slug: 'baklava-assortment-250g',
    barcode: '8902001000116',
    sku: 'SKU-BAKLAVA-250',
    description: 'Honey-soaked filo pastry assortment.',
    category: 'Pantry',
    price: 7.49,
    tags: ['arabic', 'sweets', 'pantry'],
    image: 'baklava',
  }),
  p({
    name: 'Mango Pickle 400g',
    slug: 'mango-pickle-400g',
    barcode: '8902001000117',
    sku: 'SKU-ACHAR-400',
    description: 'Spicy mango achar — South Asian condiment.',
    category: 'Pantry',
    price: 3.29,
    tags: ['india', 'pakistan', 'bangladesh', 'pickle', 'pantry'],
    image: 'pickle',
  }),
  p({
    name: 'Mixed Vegetable Pickle 400g',
    slug: 'mixed-vegetable-pickle-400g',
    barcode: '8902001000118',
    sku: 'SKU-MIXPICK-400',
    description: 'Tangy mixed vegetable pickle.',
    category: 'Pantry',
    price: 3.09,
    tags: ['india', 'pakistan', 'pickle', 'pantry'],
    image: 'mixedPickle',
  }),
  p({
    name: 'Papadum Plain (200g)',
    slug: 'papadum-plain-200g',
    barcode: '8902001000119',
    sku: 'SKU-PAPAD-200',
    description: 'Plain urad papad for frying or roasting.',
    category: 'Pantry',
    price: 1.99,
    tags: ['india', 'pakistan', 'pantry'],
    image: 'papadum',
  }),
  p({
    name: 'Vermicelli (Seviyan) 200g',
    slug: 'vermicelli-seviyan-200g',
    barcode: '8902001000120',
    sku: 'SKU-SEVIYAN-200',
    description: 'Roasted vermicelli for sheer khurma and payesh.',
    category: 'Pantry',
    price: 1.49,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'pantry'],
    image: 'vermicelli',
  }),
  p({
    name: 'Rose Water 250ml',
    slug: 'rose-water-250ml',
    barcode: '8902001000121',
    sku: 'SKU-ROSEW-250',
    description: 'Food-grade rose water for desserts and Arabic sweets.',
    category: 'Pantry',
    price: 2.49,
    tags: ['arabic', 'india', 'pakistan', 'pantry'],
    image: 'roseWater',
  }),
  p({
    name: 'Orange Blossom Water 250ml',
    slug: 'orange-blossom-water-250ml',
    barcode: '8902001000122',
    sku: 'SKU-OBLOSSOM-250',
    description: 'Orange blossom water for Levantine desserts and drinks.',
    category: 'Pantry',
    price: 2.49,
    tags: ['arabic', 'pantry'],
    image: 'orangeBlossom',
  }),
  p({
    name: 'Tamarind Paste 400g',
    slug: 'tamarind-paste-400g',
    barcode: '8902001000123',
    sku: 'SKU-IMLI-400',
    description: 'Ready tamarind paste for chutneys and curries.',
    category: 'Pantry',
    price: 2.99,
    tags: ['india', 'bangladesh', 'pantry'],
    image: 'tamarindPaste',
  }),
  p({
    name: 'Coconut Milk 400ml',
    slug: 'coconut-milk-400ml',
    barcode: '8902001000124',
    sku: 'SKU-COCO-400',
    description: 'Canned coconut milk for curries and desserts.',
    category: 'Pantry',
    price: 1.79,
    tags: ['india', 'bangladesh', 'pantry'],
    image: 'coconutMilk',
  }),

  // —— Fill taxonomy leaves to ≥5 SKUs each ——
  p({
    name: 'Chicken Drumsticks 1kg',
    slug: 'chicken-drumsticks-1kg',
    barcode: '8902001000130',
    sku: 'SKU-CDRUM-1',
    description: 'Halal chicken drumsticks for roasting and curry.',
    category: 'Meat & Poultry',
    price: 7.99,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'chicken', 'meat'],
    image: 'chickenDrumsticks',
  }),
  p({
    name: 'Frozen Chicken Legs 1kg',
    slug: 'frozen-chicken-legs-1kg',
    barcode: '8902001000131',
    sku: 'SKU-FCHICK-LEG-1',
    description: 'Frozen halal chicken legs — freezer staple.',
    category: 'Meat & Poultry',
    price: 6.49,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'chicken', 'frozen'],
    image: 'chickenLegs',
  }),
  p({
    name: 'Frozen Chicken Wings 1kg',
    slug: 'frozen-chicken-wings-1kg',
    barcode: '8902001000132',
    sku: 'SKU-FCHICK-WING-1',
    description: 'Frozen halal chicken wings.',
    category: 'Meat & Poultry',
    price: 5.99,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'chicken', 'frozen'],
    image: 'chickenWings',
  }),
  p({
    name: 'Frozen Chicken Breast 1kg',
    slug: 'frozen-chicken-breast-1kg',
    barcode: '8902001000133',
    sku: 'SKU-FCHICK-BR-1',
    description: 'Frozen boneless halal chicken breast.',
    category: 'Meat & Poultry',
    price: 9.49,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'chicken', 'frozen'],
    image: 'chickenBreast',
  }),
  p({
    name: 'Frozen Chicken Thighs 1kg',
    slug: 'frozen-chicken-thighs-1kg',
    barcode: '8902001000134',
    sku: 'SKU-FCHICK-TH-1',
    description: 'Frozen halal chicken thighs.',
    category: 'Meat & Poultry',
    price: 7.49,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'chicken', 'frozen'],
    image: 'chickenThighs',
  }),
  p({
    name: 'Frozen Whole Chicken 1.4kg',
    slug: 'frozen-whole-chicken-1-4kg',
    barcode: '8902001000135',
    sku: 'SKU-FCHICK-WH-14',
    description: 'Frozen whole halal chicken.',
    category: 'Meat & Poultry',
    price: 8.99,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'chicken', 'frozen'],
    image: 'chickenFrozen',
  }),
  p({
    name: 'Beef Steak 500g',
    slug: 'beef-steak-500g',
    barcode: '8902001000136',
    sku: 'SKU-BSTEAK-500',
    description: 'Halal beef steak cuts.',
    category: 'Meat & Poultry',
    price: 9.99,
    tags: ['pakistan', 'bangladesh', 'beef', 'meat'],
    image: 'beefSteak',
  }),
  p({
    name: 'Beef Boneless 1kg',
    slug: 'beef-boneless-1kg',
    barcode: '8902001000137',
    sku: 'SKU-BBONE-1',
    description: 'Halal boneless beef for curries and stews.',
    category: 'Meat & Poultry',
    price: 13.49,
    tags: ['pakistan', 'bangladesh', 'beef', 'meat'],
    image: 'beefBoneless',
  }),
  p({
    name: 'Beef Ribs 1kg',
    slug: 'beef-ribs-1kg',
    barcode: '8902001000138',
    sku: 'SKU-BRIBS-1',
    description: 'Halal beef ribs for slow cooking.',
    category: 'Meat & Poultry',
    price: 11.99,
    tags: ['pakistan', 'bangladesh', 'beef', 'meat'],
    image: 'beefRibs',
  }),
  p({
    name: 'Lamb Chops 500g',
    slug: 'lamb-chops-500g',
    barcode: '8902001000139',
    sku: 'SKU-LCHOPS-500',
    description: 'Halal lamb chops for grilling.',
    category: 'Meat & Poultry',
    price: 12.49,
    tags: ['arabic', 'pakistan', 'lamb', 'meat'],
    image: 'lambChops',
  }),
  p({
    name: 'Lamb Mince 500g',
    slug: 'lamb-mince-500g',
    barcode: '8902001000140',
    sku: 'SKU-LMINCE-500',
    description: 'Halal lamb mince for kebabs and keema.',
    category: 'Meat & Poultry',
    price: 7.99,
    tags: ['arabic', 'pakistan', 'india', 'lamb', 'meat'],
    image: 'lambMince',
  }),
  p({
    name: 'Goat Curry Pieces 1kg',
    slug: 'goat-curry-pieces-1kg',
    barcode: '8902001000141',
    sku: 'SKU-GOAT-1',
    description: 'Halal goat curry cuts — South Asian favourite.',
    category: 'Meat & Poultry',
    price: 14.49,
    tags: ['bangladesh', 'india', 'pakistan', 'lamb', 'meat'],
    image: 'goatMeat',
  }),
  p({
    name: 'Pomfret Fish 500g',
    slug: 'pomfret-fish-500g',
    barcode: '8902001000142',
    sku: 'SKU-POMF-500',
    description: 'Whole pomfret for Bengali and coastal curries.',
    category: 'Meat & Poultry',
    price: 12.99,
    tags: ['bangladesh', 'india', 'fish', 'meat'],
    image: 'fishPomfret',
  }),
  p({
    name: 'Salmon Fillets 400g',
    slug: 'salmon-fillets-400g',
    barcode: '8902001000143',
    sku: 'SKU-SALM-400',
    description: 'Fresh salmon fillets.',
    category: 'Meat & Poultry',
    price: 9.99,
    tags: ['arabic', 'fish', 'meat'],
    image: 'fishSalmon',
  }),
  p({
    name: 'Prawns 500g',
    slug: 'prawns-500g',
    barcode: '8902001000144',
    sku: 'SKU-PRAWN-500',
    description: 'Shelled prawns for seafood dishes.',
    category: 'Meat & Poultry',
    price: 10.49,
    tags: ['bangladesh', 'india', 'arabic', 'seafood', 'fish'],
    image: 'fishPrawns',
  }),
  p({
    name: 'Bananas 1kg',
    slug: 'bananas-1kg',
    barcode: '8902001000145',
    sku: 'SKU-BANANA-1',
    description: 'Ripe bananas for the fruit bowl.',
    category: 'Produce',
    price: 1.79,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'fruit'],
    image: 'banana',
  }),
  p({
    name: 'Red Apples 1kg',
    slug: 'red-apples-1kg',
    barcode: '8902001000146',
    sku: 'SKU-APPLE-1',
    description: 'Crisp red apples.',
    category: 'Produce',
    price: 2.49,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'fruit'],
    image: 'apple',
  }),
  p({
    name: 'Pomegranate 500g',
    slug: 'pomegranate-500g',
    barcode: '8902001000147',
    sku: 'SKU-ANAR-500',
    description: 'Fresh pomegranate — anar for salads and juice.',
    category: 'Produce',
    price: 2.99,
    tags: ['india', 'pakistan', 'arabic', 'fruit'],
    image: 'pomegranate',
  }),
  p({
    name: 'Alphonso Mangoes 1kg',
    slug: 'alphonso-mangoes-1kg',
    barcode: '8902001000148',
    sku: 'SKU-MANGO-FR-1',
    description: 'Seasonal Alphonso-style mangoes.',
    category: 'Produce',
    price: 4.99,
    tags: ['india', 'pakistan', 'bangladesh', 'fruit'],
    image: 'mango',
  }),
  p({
    name: 'Fresh Dates 400g',
    slug: 'fresh-dates-400g',
    barcode: '8902001000149',
    sku: 'SKU-FDATE-400',
    description: 'Soft fresh dates for snacking.',
    category: 'Produce',
    price: 5.49,
    tags: ['arabic', 'fruit', 'dates'],
    image: 'freshDates',
  }),
  p({
    name: 'Mint Bunch 100g',
    slug: 'mint-bunch-100g',
    barcode: '8902001000150',
    sku: 'SKU-MINT-100',
    description: 'Fresh mint for chutney, raita, and tea.',
    category: 'Produce',
    price: 0.99,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'produce'],
    image: 'mint',
  }),
  p({
    name: 'Lettuce Head 1pc',
    slug: 'lettuce-head-1pc',
    barcode: '8902001000151',
    sku: 'SKU-LETTUCE-1',
    description: 'Crisp lettuce for salads and wraps.',
    category: 'Produce',
    price: 1.29,
    tags: ['india', 'pakistan', 'arabic', 'produce'],
    image: 'lettuce',
  }),
  p({
    name: 'Methi Leaves 200g',
    slug: 'methi-leaves-200g',
    barcode: '8902001000152',
    sku: 'SKU-METHI-L-200',
    description: 'Fresh fenugreek (methi) leaves for saag.',
    category: 'Produce',
    price: 1.49,
    tags: ['india', 'pakistan', 'produce'],
    image: 'methi',
  }),
  p({
    name: 'Green Beans 500g',
    slug: 'green-beans-500g',
    barcode: '8902001000153',
    sku: 'SKU-GBEANS-500',
    description: 'Fresh green beans for stir-fry and curries.',
    category: 'Produce',
    price: 2.19,
    tags: ['india', 'pakistan', 'bangladesh', 'produce'],
    image: 'greenBeans',
  }),
  p({
    name: 'Pearl Barley 500g',
    slug: 'pearl-barley-500g',
    barcode: '8902001000154',
    sku: 'SKU-BARLEY-500',
    description: 'Pearl barley for soups and grain bowls.',
    category: 'Pantry',
    price: 2.29,
    tags: ['arabic', 'grains', 'pantry'],
    image: 'pearlBarley',
  }),
  p({
    name: 'Chapati (6 pack)',
    slug: 'chapati-6-pack',
    barcode: '8902001000155',
    sku: 'SKU-CHAPATI-6',
    description: 'Ready-to-heat plain chapati / roti.',
    category: 'Pantry',
    price: 2.19,
    tags: ['india', 'pakistan', 'bangladesh', 'bread', 'pantry'],
    image: 'chapati',
  }),
  p({
    name: 'Garlic Naan (4 pack)',
    slug: 'garlic-naan-4-pack',
    barcode: '8902001000156',
    sku: 'SKU-GNAAN-4',
    description: 'Garlic-topped naan breads.',
    category: 'Pantry',
    price: 2.79,
    tags: ['india', 'pakistan', 'bread', 'pantry'],
    image: 'garlicNaan',
  }),
  p({
    name: 'Masala Chai Tea Bags (50)',
    slug: 'masala-chai-tea-bags-50',
    barcode: '8902001000157',
    sku: 'SKU-CHAIBAG-50',
    description: 'Spiced masala chai tea bags.',
    category: 'Beverages',
    price: 3.49,
    tags: ['india', 'pakistan', 'tea', 'beverages'],
    image: 'masalaChai',
  }),
  p({
    name: 'Green Tea 100g',
    slug: 'green-tea-100g',
    barcode: '8902001000158',
    sku: 'SKU-GTEA-100',
    description: 'Light green tea leaves.',
    category: 'Beverages',
    price: 3.29,
    tags: ['india', 'bangladesh', 'arabic', 'tea', 'beverages'],
    image: 'greenTea',
  }),
  p({
    name: 'Ceylon Tea 450g',
    slug: 'ceylon-tea-450g',
    barcode: '8902001000159',
    sku: 'SKU-CTEA-450',
    description: 'Classic Ceylon leaf tea.',
    category: 'Beverages',
    price: 4.29,
    tags: ['india', 'pakistan', 'bangladesh', 'tea', 'beverages'],
    image: 'ceylonTea',
  }),
  p({
    name: 'Turkish Coffee 200g',
    slug: 'turkish-coffee-200g',
    barcode: '8902001000160',
    sku: 'SKU-TURKCOF-200',
    description: 'Finely ground Turkish-style coffee.',
    category: 'Beverages',
    price: 5.99,
    tags: ['arabic', 'coffee', 'beverages'],
    image: 'turkishCoffee',
  }),
  p({
    name: 'Instant Coffee 100g',
    slug: 'instant-coffee-100g',
    barcode: '8902001000161',
    sku: 'SKU-INSTCOF-100',
    description: 'Everyday instant coffee granules.',
    category: 'Beverages',
    price: 3.99,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'coffee'],
    image: 'instantCoffee',
  }),
  p({
    name: 'Cardamom Coffee 200g',
    slug: 'cardamom-coffee-200g',
    barcode: '8902001000162',
    sku: 'SKU-CARDCOF-200',
    description: 'Arabic coffee blend with cardamom.',
    category: 'Beverages',
    price: 6.49,
    tags: ['arabic', 'coffee', 'beverages'],
    image: 'cardamomCoffee',
  }),
  p({
    name: 'Espresso Ground Coffee 250g',
    slug: 'espresso-ground-coffee-250g',
    barcode: '8902001000163',
    sku: 'SKU-ESPCOF-250',
    description: 'Medium-dark espresso grind.',
    category: 'Beverages',
    price: 5.49,
    tags: ['arabic', 'coffee', 'beverages'],
    image: 'espressoCoffee',
  }),
  p({
    name: 'Orange Juice 1L',
    slug: 'orange-juice-1l',
    barcode: '8902001000164',
    sku: 'SKU-OJ-1',
    description: 'Chilled orange juice.',
    category: 'Beverages',
    price: 2.29,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'beverages'],
    image: 'orangeJuice',
  }),
  p({
    name: 'Lemon Squash 750ml',
    slug: 'lemon-squash-750ml',
    barcode: '8902001000165',
    sku: 'SKU-LEMSQ-750',
    description: 'Tangy lemon squash concentrate.',
    category: 'Beverages',
    price: 2.99,
    tags: ['india', 'pakistan', 'bangladesh', 'beverages'],
    image: 'lemonSquash',
  }),
  p({
    name: 'Free Range Eggs (6)',
    slug: 'free-range-eggs-6',
    barcode: '8902001000166',
    sku: 'SKU-EGGS-6',
    description: 'Half-dozen free-range eggs.',
    category: 'Dairy & Eggs',
    price: 2.29,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'eggs'],
    image: 'eggs',
  }),
  p({
    name: 'Free Range Eggs (18)',
    slug: 'free-range-eggs-18',
    barcode: '8902001000167',
    sku: 'SKU-EGGS-18',
    description: 'Family pack free-range eggs.',
    category: 'Dairy & Eggs',
    price: 5.49,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'eggs'],
    image: 'eggs',
  }),
  p({
    name: 'Organic Eggs (12)',
    slug: 'organic-eggs-12',
    barcode: '8902001000168',
    sku: 'SKU-EGGS-ORG-12',
    description: 'Organic free-range eggs.',
    category: 'Dairy & Eggs',
    price: 4.79,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'eggs'],
    image: 'organicEggs',
  }),
  p({
    name: 'Brown Eggs (12)',
    slug: 'brown-eggs-12',
    barcode: '8902001000169',
    sku: 'SKU-EGGS-BR-12',
    description: 'Box of 12 brown eggs.',
    category: 'Dairy & Eggs',
    price: 3.79,
    tags: ['india', 'pakistan', 'bangladesh', 'arabic', 'eggs'],
    image: 'brownEggs',
  }),
  p({
    name: 'Laundry Detergent 2kg',
    slug: 'laundry-detergent-2kg',
    barcode: '8902001000170',
    sku: 'SKU-LAUNDRY-2',
    description: 'Everyday laundry detergent powder.',
    category: 'Household',
    price: 6.99,
    tags: ['household', 'laundry'],
    image: 'laundryDetergent',
  }),
  p({
    name: 'Laundry Liquid 1.5L',
    slug: 'laundry-liquid-1-5l',
    barcode: '8902001000171',
    sku: 'SKU-LAUNLIQ-15',
    description: 'Concentrated laundry liquid.',
    category: 'Household',
    price: 5.99,
    tags: ['household', 'laundry'],
    image: 'laundryLiquid',
  }),
  p({
    name: 'Fabric Softener 1L',
    slug: 'fabric-softener-1l',
    barcode: '8902001000172',
    sku: 'SKU-SOFT-1',
    description: 'Fresh-scent fabric softener.',
    category: 'Household',
    price: 3.49,
    tags: ['household', 'laundry'],
    image: 'fabricSoftener',
  }),
  p({
    name: 'Stain Remover Spray 500ml',
    slug: 'stain-remover-spray-500ml',
    barcode: '8902001000173',
    sku: 'SKU-STAIN-500',
    description: 'Pre-wash laundry stain remover.',
    category: 'Household',
    price: 3.99,
    tags: ['household', 'laundry'],
    image: 'stainRemover',
  }),
  p({
    name: 'Washing Powder 5kg',
    slug: 'washing-powder-5kg',
    barcode: '8902001000174',
    sku: 'SKU-WASH-5',
    description: 'Family-size washing powder.',
    category: 'Household',
    price: 12.99,
    tags: ['household', 'laundry'],
    image: 'washingPowder',
  }),
];

export function culturalProductToCsvRow(row: CulturalProductSeed): string {
  const tags = row.tags.join('|');
  const esc = (v: string) => {
    if (/[",\n]/.test(v)) return `"${v.replace(/"/g, '""')}"`;
    return v;
  };
  return [
    esc(row.name),
    esc(row.slug),
    esc(row.category),
    esc(row.description),
    esc(row.imageUrl),
    esc(tags),
    'true',
    esc(row.barcode),
    esc(row.sku),
  ].join(',');
}

export function culturalProductsCsv(): string {
  const header =
    'name,slug,category,description,image_url,tags,is_active,barcode,sku';
  return [header, ...CULTURAL_PRODUCT_BANK.map(culturalProductToCsvRow)].join(
    '\n',
  );
}
